version: '3.8'
name: hackathon-work-container
services:
  frontend:
    container_name: react-container
    build: 
      dockerfile: Dockerfile.react
    expose:
      - "3000"
    ports:
      - 0.0.0.0:3000:3000
    depends_on:
      - backend
    networks:
      - hackathon-network

  backend:
    container_name: flask-container
    build: 
      dockerfile: Dockerfile.flask
    expose:
      - "5000"
    depends_on:
      - voicevox
    networks:
      - hackathon-network

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox-container
    networks:
      - hackathon-network
    expose:
      - "50021"
networks:
  hackathon-network: